# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 158aecac0ed3b5bf6aad049611b8b049fe5d5865e08b86e26fcda12b57c9184d8d0fe187bb21bb7ec7bca49b2ada79f161a34a707596d01a7156176d5c4a43ca

test:
  secret_key_base: 3092336d07267b8f2c3475122862c355f3d6bcedd50d0b5476dcdadccf7a5f4edf6428c0d41b948abf4d9702113c98db892f41ede98423020e2e7eb7f49e1dc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
